routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('/', function () {
    return redirect('admin');
});
Route::group(['middleware' => 'auth','prefix' => 'admin'],function (){

    //Route::get('/', function () {
    //    return view('dashboard.home');
    //});
    Route::get('/', 'HomeController@index');
    Route::get('profit_report', 'HomeController@report');
    Route::get('transaction_report/{id}', 'HomeController@photographer_transactions');
    Route::resource('admin','UserController');
    Route::resource('about_app','AboutappController');
    Route::resource('reason','ReasonsmsgController');
    Route::resource('message','ContactusController');
    Route::resource('city','CityController');

    Route::resource('category','CategoryController');
    Route::get('category/{id}/enabled', 'CategoryController@enabled');
    Route::get('category/{id}/disabled', 'CategoryController@disabled');

    Route::resource('customer','CustomerController');
    Route::get('customer/{id}/enabled', 'CustomerController@enabled');
    Route::get('customer/{id}/disabled', 'CustomerController@disabled');

    Route::resource('photographer','PhotographerController');
    Route::get('photographer/{id}/enabled', 'PhotographerController@enabled');
    Route::get('photographer/{id}/disabled', 'PhotographerController@disabled');

    Route::resource('service','ServiceController');
    Route::get('service/{id}/enabled', 'ServiceController@enabled');
    Route::get('service/{id}/disabled', 'ServiceController@disabled');

    Route::resource('reservation','ReservationController');

    Route::get('notification', 'NotificationController@view');
    Route::post('notification', 'NotificationController@send');


});

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class City extends Model 
{

    protected $table = 'cities';
    public $timestamps = true;

    use SoftDeletes;

    protected $dates = ['deleted_at'];
    protected $fillable = array('country_id', 'name_ar', 'name_en');
    protected $appends = ['name'];
    protected $hidden = ['name_ar', 'name_en', 'enabled', 'created_at', 'deleted_at', 'updated_at'];

    protected $casts = [
        'id' => 'integer',
        'country_id' =>'integer',

    ];

    public function country()
    {
        return $this->belongsTo('App\Models\Country');
    }

    public function customers()
    {
        return $this->hasMany('App\Models\Customer');
    }

    public function photographers()
    {
        return $this->hasMany('App\Models\Photographer');
    }

    public function getNameAttribute() {
        if (request()->header('Accept-Language') == 'ar') {
            return $this->name_ar;
        }

        return $this->name_en;
    }

    public function scopeEnabled($q) {
        $q->where('enabled', 1);
    }

}

app/Http/Controllers/CityController.php
<?php 

namespace App\Http\Controllers;

use App\Models\City;
use Illuminate\Http\Request;

class CityController extends Controller
{

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
      $cities = City::paginate(12);
      return view('dashboard.cities.index',compact('cities'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
      $model = new City;
      return view('dashboard.cities.create',compact('model'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      $rules = [
          'name_ar' => 'required',
          'name_en' => 'required',

      ];

      $messages = [
          'name_ar.required' => 'الاسم بالعربية مطلوب',
          'name_en.required' => 'الاسم بالانجليزية مطلوب',

      ];

      $this->validate($request,$rules,$messages);

      $request->country_id='1';

      $city = City::create($request->all());


      if ($city) {
          flash()->success('تمت الاضافة');
          return redirect('admin/city');
      }else{
          flash()->error('حدث خطأ');
          return back();
      }
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
      $model = City::find($id);
      return view('dashboard.cities.index',compact('model'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
      $model = City::find($id);
      return view('dashboard.cities.edit',compact('model'));

  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update(Request $request,$id)
  {
      $rules = [
          'name_ar' => 'required',
          'name_en' => 'required',

      ];

      $messages = [
          'name_ar.required' => 'الاسم بالعربية مطلوب',
          'name_en.required' => 'الاسم بالانجليزية مطلوب',

      ];
      $request->merge(array('country_id' => '1'));

      $this->validate($request,$rules,$messages);



      $city = City::findOrFail($id);
      $city->update($request->all());



      if ($city) {
          flash()->success('تم التعديل');
          return redirect('admin/city');
      }else{
          flash()->error('حدث خطأ');
          return back();
      }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
      $distroy = City::findOrFail($id);

      $distroy->delete();

      if ($distroy) {
          flash()->success('تم حذف المدينة بنجاح');
          return redirect('admin/city');
      }else{
          flash()->error('حدث خطأ');
          return back();
      }
  }
  
}

?>

resources/views/dashboard/cities/create.blade.php
@extends('dashboard.master',[
                                'page_title'       => 'المدن'
                                ])

@section('content')

    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>'CityController@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST'
                            ])!!}
        @include('dashboard.cities.form')
        <button type="submit" class="btn btn-primary">حفظ</button>
    {!! Form::close()!!}
@stop

resources/views/dashboard/cities/edit.blade.php
@extends('dashboard.master',[
                                'page_title'       => 'المدن'
                                ])

@section('content')
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>['CityController@update',$model->id],
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'PUT'
                            ])!!}
    @include('dashboard.cities.form')
    <button type="submit" class="btn btn-primary">حفظ</button>
    {!! Form::close()!!}
@stop

resources/views/dashboard/cities/form.blade.php
@include('dashboard.partials.validation-errors')
@include('flash::message')

<div class="form-group">
    <label for="">الاسم بالعربية</label>
    {!! Form::text('name_ar', null ,[
        'class' => 'form-control',
        'placeholder' => 'الاسم'
    ])!!}
</div>

<div class="form-group">
    <label for="">الاسم بالانجليزية</label>
    {!! Form::text('name_en', null ,[
        'class' => 'form-control',
        'placeholder' => 'City name'
    ])!!}
</div>

resources/views/dashboard/cities/index.blade.php
@extends('dashboard.master',[
                                'page_title'       => 'المدن'
                                ])
@section('content')
    @include('flash::message')
    @if(count($cities))
        <div class="col-md-12">
            <a href="{{url('admin/city/create')}}" class="btn btn-info">اضافة مدينة جديدة</a>
        </div>
        <br>
        <br>
        <div class="clearfix"></div>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <th>#</th>
                <th>الاسم بالعربية</th>
                <th>الاسم بالانجليزية</th>
                <th class="text-center">تعديل</th>
                <th class="text-center">حذف</th>
                </thead>
                <tbody>
                @php $count = 1; @endphp
                @foreach($cities as $city)
                    <tr id="removable{{$city->id}}">
                        <td>{{$count}}</td>
                        <td>{{$city->name_ar}}</td>
                        <td>{{$city->name_en}}</td>
                        <td class="text-center"><a href="city/{{$city->id}}/edit" class="btn btn-xs btn-success"><i class="fa fa-edit"></i></a></td>
                        <td class="center">
                            <a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#delete{{$city->id}}"><i class="entypo-trash"></i></a>
                        </td>
                        {{--<td class="text-center">--}}
                        {{--<button id="{{$city->id}}" data-token="{{ csrf_token() }}" data-route="{{URL::route('city.destroy',$city->id)}}"  type="button" class="destroy btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>--}}
                        {{--</td>--}}






                    </tr>
                    <div id="delete{{$city->id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">حذف المدينة</h4>
                                </div>
                                <div class="modal-body">
                                    <p>هل أنت متأكد من حذف المدينة {{$city->name_ar}} ؟</p>
                                </div>
                                <div class="modal-footer">
                                    {!! Form::model($city,[
                                'action'=>['CityController@destroy',$city->id],
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'delete'
                                ])!!}
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                    {!! Form::close()!!}
                                    <button type="button" class="btn btn-default" data-dismiss="modal">لا</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    @php $count ++; @endphp
                @endforeach
                </tbody>
            </table>
        </div>
        {!! $cities->render() !!}
    @endif
@endsection