routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('/', function () {
    return redirect('admin');
});
Route::group(['middleware' => 'auth','prefix' => 'admin'],function (){

    //Route::get('/', function () {
    //    return view('dashboard.home');
    //});
    Route::get('/', 'HomeController@index');
    Route::get('profit_report', 'HomeController@report');
    Route::get('transaction_report/{id}', 'HomeController@photographer_transactions');
    Route::resource('admin','UserController');
    Route::resource('about_app','AboutappController');
    Route::resource('reason','ReasonsmsgController');
    Route::resource('message','ContactusController');
    Route::resource('city','CityController');

    Route::resource('category','CategoryController');
    Route::get('category/{id}/enabled', 'CategoryController@enabled');
    Route::get('category/{id}/disabled', 'CategoryController@disabled');

    Route::resource('customer','CustomerController');
    Route::get('customer/{id}/enabled', 'CustomerController@enabled');
    Route::get('customer/{id}/disabled', 'CustomerController@disabled');

    Route::resource('photographer','PhotographerController');
    Route::get('photographer/{id}/enabled', 'PhotographerController@enabled');
    Route::get('photographer/{id}/disabled', 'PhotographerController@disabled');

    Route::resource('service','ServiceController');
    Route::get('service/{id}/enabled', 'ServiceController@enabled');
    Route::get('service/{id}/disabled', 'ServiceController@disabled');

    Route::resource('reservation','ReservationController');

    Route::get('notification', 'NotificationController@view');
    Route::post('notification', 'NotificationController@send');


});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{

    protected $table = 'categories';
    public $timestamps = true;

    use SoftDeletes;

    protected $dates = ['deleted_at'];
    protected $fillable = array('name_ar', 'name_en','icon');
    protected $appends = ['name'];
    protected $hidden = ['name_ar', 'name_en', 'enabled', 'created_at', 'deleted_at', 'updated_at'];

    // casting attributes to return proper types with json
    protected $casts = [
        'id' => 'integer',
    ];

    public function services()
    {
        return $this->hasMany('App\Models\Service');
    }

    public function portfolios()
    {
        return $this->hasMany('App\Models\Portfolio');
    }

    public function getNameAttribute() {
        if (request()->header('Accept-Language') == 'ar') {
            return $this->name_ar;
        }

        return $this->name_en;
    }

    public function scopeEnabled($q) {
        $q->where('enabled', 1);
    }

    public function getIconAttribute($value) {
        if ($value == null) { return ""; }
        return (string) $value;
    }

}

app/Http/Controllers/CategoryController.php
<?php 

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
      $categories = Category::paginate(12);
      return view('dashboard.categories.index',compact('categories'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
      $model = new Category;
      return view('dashboard.categories.create',compact('model'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(Request $request)
  {
      $rules = [
          'name_ar' => 'required',
          'name_en' => 'required',
          'icon' => 'required',
      ];

      $messages = [
          'name_ar.required' => 'الاسم مطلوب',
          'name_en.required' => 'الاسم مطلوب',
          'icon.required' => 'صورة القسم مطلوبة',
      ];

      $this->validate($request,$rules,$messages);
      $category = Category::create($request->except('icon'));
      if($request->hasFile('icon')){
          $path = base_path();

          $destinationPath = $path.'/uploads'; // upload path
          $photo= $request->file('icon');
          $extension = $photo->getClientOriginalExtension(); // getting image extension
          $name = time().''.rand(11111,99999).'.'.$extension; // renaming image
          $photo->move($destinationPath, $name); // uploading file to given path
          $category->icon  = 'uploads/'.$name ;
          $category->save();
      }

      if ($category) {
          flash()->success('تمت الاضافة');
          return redirect('admin/category');
      }else{
          flash()->error('حدث خطأ');
          return back();
      }
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
      $model = Category::find($id);
      return view('dashboard.categories.index',compact('model'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
      $model = Category::find($id);
      return view('dashboard.categories.edit',compact('model'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update(Request $request,$id)
  {
      $rules = [
          'name_ar' => 'required',
          'name_en' => 'required',
      ];

      $messages = [
          'name_ar.required' => 'الاسم مطلوب',
          'name_en.required' => 'الاسم مطلوب',
      ];

      $this->validate($request,$rules,$messages);

      $category = Category::find($id);
      $category2 = $category->update($request->except('icon'));
      if($request->hasFile('icon')){
          $path = base_path();
          $destinationPath = $path.'/uploads'; // upload path
          $photo= $request->file('icon');
          $extension = $photo->getClientOriginalExtension(); // getting image extension
          $name = time().''.rand(11111,99999).'.'.$extension; // renaming image
          $photo->move($destinationPath, $name); // uploading file to given path
          $category->icon  = 'uploads/'.$name ;
          $category->save();
      }

      if ($category2) {
          flash()->success('تمم التعديل');
          return redirect('admin/category');
      }else{
          flash()->error('حدث خطأ');
          return back();
      }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
      $distroy = Category::findOrFail($id);

      $distroy->delete();

      if ($distroy) {
          flash()->success('تم حذف القسم بنجاح');
          return redirect('admin/category');
      }else{
          flash()->error('حدث خطأ');
          return back();
      }
  }

    public function enabled($id)
    {
        $model = Category::findOrFail($id);
        $model->enabled = 1;
        $model->save();
        flash()->success('تم التفعيل');
        return back();
    }

    public function disabled($id)
    {
        $model = Category::findOrFail($id);
        $model->enabled = 0;
        $model->save();
        flash()->success('تم إلغاء التفعيل');
        return back();
    }

  
}

?>

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.master',[
                                'page_title'       => 'الأقسام'
                                ])

@section('content')

    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>'CategoryController@store',
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'POST',
                            'enctype'=>'multipart/form-data'
                            ])!!}
        @include('dashboard.categories.form')
        <button type="submit" class="btn btn-primary">حفظ</button>
    {!! Form::close()!!}
@stop

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.master',[
                                'page_title'       => 'الأقسام'
                                ])

@section('content')
    <!-- form start -->
    {!! Form::model($model,[
                            'action'=>['CategoryController@update',$model->id],
                            'id'=>'myForm',
                            'role'=>'form',
                            'method'=>'PUT',
                            'enctype'=>'multipart/form-data'
                            ])!!}
    @include('dashboard.categories.form')
    <button type="submit" class="btn btn-primary">حفظ</button>
    {!! Form::close()!!}
@stop

resources/views/dashboard/categories/form.blade.php
@include('dashboard.partials.validation-errors')
@include('flash::message')

<div class="form-group">
    <label for="">القسم بالعربية</label>
    {!! Form::text('name_ar', null ,[
        'class' => 'form-control',
        'placeholder' => 'القسم'
    ])!!}
</div>

<div class="form-group">
    <label for="">القسم بالانجليزية</label>
    {!! Form::text('name_en', null ,[
        'class' => 'form-control',
        'placeholder' => 'category'
    ])!!}
</div>

<div class="form-group">
    <label for="">ايفونة القسم</label>
    {!! Form::file('icon', null ,[
        'class' => 'form-control',
        'placeholder' => 'ايقونة'
    ])!!}
</div>

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.master',[
                                'page_title'       => 'أسباب التواصل'
                                ])
@section('content')
    @include('flash::message')
    @if(count($categories))
        <div class="col-md-12">
            <a href="{{url('admin/category/create')}}" class="btn btn-info">اضافة قسم جديد</a>
        </div>
        <br>
        <br>
        <div class="clearfix"></div>
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                <th>#</th>
                <th>الاسم بالعربية</th>
                <th>الاسم بالانجليزية</th>
                <th>ايقونة القسم</th>
                <th>الحالة</th>
                <th class="text-center">تعديل</th>
                <th class="text-center">حذف</th>
                </thead>
                <tbody>
                @php $count = 1; @endphp
                @foreach($categories as $category)
                    <tr id="removable{{$category->id}}">
                        <td>{{$count}}</td>
                        <td>{{$category->name_ar}}</td>
                        <td>{{$category->name_en}}</td>
                        <td><img  style="max-height:60px;" src="../../{{$category->icon}}"></td>
                        <td class="text-center">
                            @if($category->enabled)
                                <a href="category/{{$category->id}}/disabled" class="btn btn-xs btn-success"><i class="fa fa-check"></i> مفعل</a>
                            @else
                                <a href="category/{{$category->id}}/enabled" class="btn btn-xs btn-danger"><i class="fa fa-close"></i> غير مفعل</a>
                            @endif
                        </td>
                        <td class="text-center"><a href="category/{{$category->id}}/edit" class="btn btn-xs btn-success"><i class="fa fa-edit"></i></a></td>
                        <td class="center">
                            <a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#delete{{$category->id}}"><i class="entypo-trash"></i></a>
                        </td>
                        {{--<td class="text-center">--}}
                        {{--<button id="{{$category->id}}" data-token="{{ csrf_token() }}" data-route="{{URL::route('category.destroy',$category->id)}}"  type="button" class="destroy btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>--}}
                        {{--</td>--}}






                    </tr>
                    <div id="delete{{$category->id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">حذف القسم</h4>
                                </div>
                                <div class="modal-body">
                                    <p>هل أنت متأكد من حذف القسم {{$category->name_ar}} ؟</p>
                                </div>
                                <div class="modal-footer">
                                    {!! Form::model($category,[
                                'action'=>['CategoryController@destroy',$category->id],
                                'id'=>'myForm',
                                'role'=>'form',
                                'method'=>'delete'
                                ])!!}
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                    {!! Form::close()!!}
                                    <button type="button" class="btn btn-default" data-dismiss="modal">لا</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    @php $count ++; @endphp
                @endforeach
                </tbody>
            </table>
        </div>
        {!! $categories->render() !!}
    @endif
@endsection